site_name: jQuery Technical Report
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Features: features.md
  - Usage: usage.md
  - Advanced Topics: advanced.md
  - References: references.md

theme:
  name: 'swan'
  highlightjs: true